# Implementing Support Vector Machine using sklearn

**Importing necessary libraries and datasets**

In [1]:
import numpy as np
from sklearn import datasets,metrics,svm

**Dividing the data into training set and testing set**

In [2]:
X,y = datasets.load_iris(return_X_y=True)

X_train = X[range(0,150,2),:]
y_train = y[range(0,150,2)]

X_test = X[range(1,150,2),:]
y_test = y[range(0,150,2)]

**Performing Classification using svm**

In [3]:
# initializing the clf variable and fitting the training set to it
clf = svm.LinearSVC(max_iter=10000).fit(X_train,y_train)

# predicting the values
prediction = clf.predict(X_test)
prediction

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1,
       1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2,
       1, 2, 2, 2, 2, 2, 2, 2, 2])

**Testing our model**

In [4]:
#calculating various metrics
print("\n-------------------------Accuracy Score----------------------------\n\t\t\t     ",metrics.accuracy_score(y_test, prediction, normalize= True))
print("\n---------------------Classification Report-------------------------\n",metrics.classification_report(y_test, prediction))
print("\n--------------------------Confusion Matrix-------------------------\n",metrics.confusion_matrix(y_test,prediction))


-------------------------Accuracy Score----------------------------
			      0.96

---------------------Classification Report-------------------------
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        25
           1       0.92      0.96      0.94        25
           2       0.96      0.92      0.94        25

    accuracy                           0.96        75
   macro avg       0.96      0.96      0.96        75
weighted avg       0.96      0.96      0.96        75


--------------------------Confusion Matrix-------------------------
 [[25  0  0]
 [ 0 24  1]
 [ 0  2 23]]
