# Implementing Multivariate Linear Regression using Normal Equation

**Importing necessary libraries and datasets**

In [1]:
import numpy as np
from sklearn import metrics, datasets
from sklearn.preprocessing import StandardScaler

In [2]:
X,y = datasets.load_boston(return_X_y = True)
X.shape

(506, 13)

**Dividing the data into training set and testing set**

In [3]:
X_train = X[0:400,:]

# create a temp array with all zeros of shape (400,14) for adding one extra column of ones
shape_tuple = (X_train.shape[0], X_train.shape[1] + 1);
X_temp = np.zeros(shape_tuple)
print(X_temp.shape)

# create a column vector of shape (400,1) containing all the ones for X0
column1 = np.ones(X_train.shape[0])
print(column1.shape)

# add this column as the first column of X_temp
X_temp[:,0] = column1;
print(X_temp)

# add the rest of the training data to it and finally assign it back to X_train
X_temp[:,1:] = X_train;
X_train = X_temp;
print(X_train.shape)


# getting our y_train vector
y_train = y[0:400]
print(y_train.shape)

(400, 14)
(400,)
[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]]
(400, 14)
(400,)


In [4]:
# remaining data will be our testing data

X_test = X[400:,:]
print(X_test.shape)

# create a temp array with all zeros of shape (400,14) for adding one extra column of ones
shape_tuple = (X_test.shape[0], X_test.shape[1] + 1);
X_temp = np.zeros(shape_tuple)

# create a column vector of shape (400,1) containing all the ones for X0
column1 = np.ones(X_test.shape[0])

# add this column as the first column of X_temp
X_temp[:,0] = column1;

# add the rest of the training data to it and finally assign it back to X_train
X_temp[:,1:] = X_test;
X_test = X_temp;
print(X_test.shape)

# getting our y_test vector
y_test = y[400:]
print(y_test.shape)

(106, 13)
(106, 14)
(106,)


**Performing feature scaling**

In [5]:
# initializing the theta vector with random uniform values between 0 and 1
# shape of theta is (14,1)
theta = np.random.uniform(0,1,X_train.shape[1])
print(theta)

# feature scaling the X_train data to bring the range of values of all columns in [0,1]
scaler = StandardScaler()

# ftting the data (i.e. finding out the mean and standard dev for normalization)
scaler.fit(X_train[:,1:])

# scaling the data and assigning it back to X_train and X_test
X_train[:,1:] = scaler.transform(X_train[:,1:])
X_test[:,1:] = scaler.transform(X_test[:,1:])

[0.25939161 0.13937054 0.6543821  0.58423391 0.007476   0.71258085
 0.78242977 0.87455345 0.63840011 0.70434336 0.8823507  0.02305933
 0.81616567 0.13876941]


**Applying Normal Equation**

In [6]:
A = np.linalg.pinv(np.dot(X_train.T,X_train))
B = np.dot(X_train.T,y_train)

theta = np.dot(A,B)
theta

array([24.3345    , -1.14370921,  1.12191092,  0.35913222,  0.48497247,
       -1.7061696 ,  3.58169796,  0.07554815, -2.8156326 ,  3.05189603,
       -1.97502535, -1.7937352 , -0.05252128, -3.50239563])

**Testing our model**

In [7]:
prediction = np.dot(X_test,theta)

print("MAE", metrics.mean_absolute_error(y_true=y_test,y_pred = prediction))
print("MSE", metrics.mean_squared_error(y_true=y_test,y_pred = prediction))

MAE 5.14223221446533
MSE 37.89377859960243
