# Implementing MLP Classifier and K-Means Clustering

# 1. MLP Classifier

**Impoting necessary libraries and datasets**

In [1]:
import numpy as np
from sklearn import datasets, metrics
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split

**Dividing the data into training set and testing set**

In [2]:
X,y = datasets.load_iris(return_X_y=True)

X_train = X[range(0,150,2),:]
y_train = y[range(0,150,2)]

X_test = X[range(1,150,2),:]
y_test = y[range(0,150,2)]

print(X_train.shape)
print(X_test.shape)

(75, 4)
(75, 4)


**Applying variations to MLPClassifier to compare the Accuracy** 

**Variation 1**

In [3]:
classifier = MLPClassifier(solver='sgd', hidden_layer_sizes=(65), max_iter= 1200, activation='relu', learning_rate = 'constant')
classifier.fit(X_train,y_train);


prediction = classifier.predict(X_test)
prediction

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1,
       1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       1, 2, 2, 2, 2, 2, 2, 2, 2])

**Testing our Model**

In [4]:
#calculating various metrics
print("\n-------------------------Accuracy Score----------------------------\n\t\t\t     ",metrics.accuracy_score(y_test, prediction, normalize= True))
print("\n---------------------Classification Report-------------------------\n",metrics.classification_report(y_test, prediction))
print("\n--------------------------Confusion Matrix-------------------------\n",metrics.confusion_matrix(y_test,prediction))
print("\n------------------Probabilities for each class---------------------\n",classifier.predict_proba(X_test))


-------------------------Accuracy Score----------------------------
			      0.9733333333333334

---------------------Classification Report-------------------------
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        25
           1       0.96      0.96      0.96        25
           2       0.96      0.96      0.96        25

    accuracy                           0.97        75
   macro avg       0.97      0.97      0.97        75
weighted avg       0.97      0.97      0.97        75


--------------------------Confusion Matrix-------------------------
 [[25  0  0]
 [ 0 24  1]
 [ 0  1 24]]

------------------Probabilities for each class---------------------
 [[9.69674088e-01 3.03217217e-02 4.19041927e-06]
 [9.63243239e-01 3.67486513e-02 8.10929888e-06]
 [9.87536137e-01 1.24631635e-02 6.99211630e-07]
 [9.81580130e-01 1.84183045e-02 1.56569984e-06]
 [9.70105661e-01 2.98908480e-02 3.49059664e-06]
 [9.74414874e-01 2.55816773e-02 3.4

**Variation 2**

In [5]:
classifier = MLPClassifier(solver='sgd', hidden_layer_sizes=(200), max_iter= 2500, activation='logistic', learning_rate = 'adaptive')
classifier.fit(X_train,y_train);

prediction = classifier.predict(X_test)
prediction

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 1,
       1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2])

**Testing our Model**

In [6]:
#calculating various metrics
print("\n-------------------------Accuracy Score----------------------------\n\t\t\t     ",metrics.accuracy_score(y_test, prediction, normalize= True))
print("\n---------------------Classification Report-------------------------\n",metrics.classification_report(y_test, prediction))
print("\n--------------------------Confusion Matrix-------------------------\n",metrics.confusion_matrix(y_test,prediction))
print("\n------------------Probabilities for each class---------------------\n",classifier.predict_proba(X_test))


-------------------------Accuracy Score----------------------------
			      0.9733333333333334

---------------------Classification Report-------------------------
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        25
           1       1.00      0.92      0.96        25
           2       0.93      1.00      0.96        25

    accuracy                           0.97        75
   macro avg       0.98      0.97      0.97        75
weighted avg       0.98      0.97      0.97        75


--------------------------Confusion Matrix-------------------------
 [[25  0  0]
 [ 0 23  2]
 [ 0  0 25]]

------------------Probabilities for each class---------------------
 [[9.27812435e-01 7.17622369e-02 4.25328136e-04]
 [9.20373506e-01 7.90977737e-02 5.28720643e-04]
 [9.29996128e-01 6.95232272e-02 4.80644537e-04]
 [9.35954989e-01 6.36783498e-02 3.66660890e-04]
 [9.27597950e-01 7.19714526e-02 4.30597010e-04]
 [9.25204552e-01 7.43010439e-02 4.9

In [7]:
#variation 3
classifier = MLPClassifier(solver='sgd', hidden_layer_sizes=(65), max_iter= 700, activation='identity', learning_rate = 'invscaling')
classifier.fit(X_train,y_train);

prediction = classifier.predict(X_test)
prediction

array([0, 0, 2, 0, 0, 0, 0, 2, 0, 0, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2,
       0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 1, 1, 1, 2, 2])

In [8]:
#calculating various metrics
print("\n-------------------------Accuracy Score----------------------------\n\t\t\t     ",metrics.accuracy_score(y_test, prediction, normalize= True))
print("\n---------------------Classification Report-------------------------\n",metrics.classification_report(y_test, prediction))
print("\n--------------------------Confusion Matrix-------------------------\n",metrics.confusion_matrix(y_test,prediction))
print("\n------------------Probabilities for each class---------------------\n",classifier.predict_proba(X_test))


-------------------------Accuracy Score----------------------------
			      0.5333333333333333

---------------------Classification Report-------------------------
               precision    recall  f1-score   support

           0       1.00      0.80      0.89        25
           1       0.00      0.00      0.00        25
           2       0.40      0.80      0.53        25

    accuracy                           0.53        75
   macro avg       0.47      0.53      0.47        75
weighted avg       0.47      0.53      0.47        75


--------------------------Confusion Matrix-------------------------
 [[20  0  5]
 [ 0  0 25]
 [ 0  5 20]]

------------------Probabilities for each class---------------------
 [[0.4338368  0.22719542 0.33896778]
 [0.4190594  0.23455611 0.34638449]
 [0.36537565 0.26069525 0.3739291 ]
 [0.41773045 0.23347677 0.34879278]
 [0.4500337  0.21704843 0.33291788]
 [0.41100793 0.23695257 0.3520395 ]
 [0.4364783  0.22622575 0.33729596]
 [0.35267923 0.26558427

In [9]:
#variation 4
classifier = MLPClassifier(solver='sgd', hidden_layer_sizes=(65), max_iter= 2200, activation='identity', learning_rate = 'adaptive')
classifier.fit(X_train,y_train);

prediction = classifier.predict(X_test)
prediction

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1,
       1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2,
       1, 2, 2, 2, 2, 2, 2, 2, 2])

In [10]:
#calculating various metrics
print("\n-------------------------Accuracy Score----------------------------\n\t\t\t     ",metrics.accuracy_score(y_test, prediction, normalize= True))
print("\n---------------------Classification Report-------------------------\n",metrics.classification_report(y_test, prediction))
print("\n--------------------------Confusion Matrix-------------------------\n",metrics.confusion_matrix(y_test,prediction))
print("\n------------------Probabilities for each class---------------------\n",classifier.predict_proba(X_test))


-------------------------Accuracy Score----------------------------
			      0.96

---------------------Classification Report-------------------------
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        25
           1       0.92      0.96      0.94        25
           2       0.96      0.92      0.94        25

    accuracy                           0.96        75
   macro avg       0.96      0.96      0.96        75
weighted avg       0.96      0.96      0.96        75


--------------------------Confusion Matrix-------------------------
 [[25  0  0]
 [ 0 24  1]
 [ 0  2 23]]

------------------Probabilities for each class---------------------
 [[9.67334218e-01 3.26654457e-02 3.36237165e-07]
 [9.60245394e-01 3.97538745e-02 7.31237009e-07]
 [9.86608553e-01 1.33913972e-02 4.98053296e-08]
 [9.78406995e-01 2.15928859e-02 1.18861596e-07]
 [9.61597242e-01 3.84024575e-02 3.00216951e-07]
 [9.69691305e-01 3.03083960e-02 2.98726581e-07]
 

In [11]:
#splitting into train an test dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=1)
print(X_train.shape)
print(X_test.shape)

#variation 5
classifier = MLPClassifier(solver='sgd', hidden_layer_sizes=(65), max_iter= 2200, activation='tanh', learning_rate = 'adaptive')
classifier.fit(X_train,y_train)

prediction = classifier.predict(X_test)
prediction

(100, 4)
(50, 4)


array([0, 1, 1, 0, 2, 1, 2, 0, 0, 2, 1, 0, 2, 1, 1, 0, 1, 1, 0, 0, 1, 2,
       1, 0, 2, 1, 0, 0, 1, 2, 1, 2, 1, 2, 2, 0, 1, 0, 1, 2, 2, 0, 2, 2,
       1, 2, 0, 0, 0, 1])

In [12]:
#calculating various metrics
print("\n-------------------------Accuracy Score----------------------------\n\t\t\t     ",metrics.accuracy_score(y_test, prediction, normalize= True))
print("\n---------------------Classification Report-------------------------\n",metrics.classification_report(y_test, prediction))
print("\n--------------------------Confusion Matrix-------------------------\n",metrics.confusion_matrix(y_test,prediction))
print("\n------------------Probabilities for each class---------------------\n",classifier.predict_proba(X_test))


-------------------------Accuracy Score----------------------------
			      0.98

---------------------Classification Report-------------------------
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        17
           1       1.00      0.95      0.97        19
           2       0.93      1.00      0.97        14

    accuracy                           0.98        50
   macro avg       0.98      0.98      0.98        50
weighted avg       0.98      0.98      0.98        50


--------------------------Confusion Matrix-------------------------
 [[17  0  0]
 [ 0 18  1]
 [ 0  0 14]]

------------------Probabilities for each class---------------------
 [[9.93761038e-01 6.23791379e-03 1.04857872e-06]
 [1.39901758e-01 8.39208322e-01 2.08899201e-02]
 [2.28831438e-02 8.98819264e-01 7.82975926e-02]
 [9.90599528e-01 9.39784837e-03 2.62396437e-06]
 [8.49772187e-04 2.09294014e-01 7.89856214e-01]
 [1.26449497e-02 6.89544832e-01 2.97810219e-01]
 

In [13]:
#splitting into train an test dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=20)
print(X_train.shape)
print(X_test.shape)

#variation 6
classifier = MLPClassifier(solver='sgd', hidden_layer_sizes=(50), max_iter= 2100, activation='relu', learning_rate = 'constant')
classifier.fit(X_train,y_train)

#printing the results
prediction = classifier.predict(X_test)
prediction

(112, 4)
(38, 4)


array([0, 1, 1, 2, 1, 1, 2, 0, 2, 0, 2, 1, 2, 0, 0, 2, 0, 1, 2, 1, 1, 2,
       2, 0, 2, 1, 1, 0, 2, 2, 1, 1, 0, 0, 0, 2, 1, 0])

In [14]:
#calculating various metrics
print("\n-------------------------Accuracy Score----------------------------\n\t\t\t     ",metrics.accuracy_score(y_test, prediction, normalize= True))
print("\n---------------------Classification Report-------------------------\n",metrics.classification_report(y_test, prediction))
print("\n--------------------------Confusion Matrix-------------------------\n",metrics.confusion_matrix(y_test,prediction))
print("\n------------------Probabilities for each class---------------------\n",classifier.predict_proba(X_test))


-------------------------Accuracy Score----------------------------
			      0.9736842105263158

---------------------Classification Report-------------------------
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      0.93      0.96        14
           2       0.92      1.00      0.96        12

    accuracy                           0.97        38
   macro avg       0.97      0.98      0.97        38
weighted avg       0.98      0.97      0.97        38


--------------------------Confusion Matrix-------------------------
 [[12  0  0]
 [ 0 13  1]
 [ 0  0 12]]

------------------Probabilities for each class---------------------
 [[9.78452575e-01 2.15446490e-02 2.77625549e-06]
 [5.68315031e-03 7.71591266e-01 2.22725583e-01]
 [1.65369647e-02 9.35968672e-01 4.74943629e-02]
 [3.94995792e-04 3.69497834e-01 6.30107171e-01]
 [2.04434674e-02 9.21726673e-01 5.78298597e-02]
 [1.13011201e-02 7.93501292e-01 1.9

# K-mean clustering

In [15]:
#importing libraries
from sklearn import datasets,metrics
from sklearn.cluster import KMeans

#loading the dataset
X,y = datasets.load_iris(return_X_y=True)

#train and test set
X_train = X[0:100,:]
X_test = X[100:,:]

#defining the model with 3 clusters, 3 centroids 
model = KMeans(n_clusters=3).fit(X_train)

#print label for each point
print("Labels:\n",model.labels_)

#print prediction on test set
prediction = model.predict(X_test)
print("Prediction:\n",prediction)

#printing coordinates of cluster centers
print("Cluster Center:\n",model.cluster_centers_)

Labels:
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 2 0 0 0 2 0 2 2 0 2 0 2 0 0 2 0 2 0 2 0 0
 0 0 0 0 0 2 2 2 2 0 2 0 0 0 2 2 2 0 2 2 2 2 2 0 2 2]
Prediction:
 [0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0]
Cluster Center:
 [[6.30769231 2.92307692 4.60769231 1.45769231]
 [5.006      3.428      1.462      0.246     ]
 [5.53333333 2.60416667 3.88333333 1.18333333]]


In [16]:
#train and test set
X_train = X[range(0,150,2),:]
X_test = X[range(1,150,2),:]

#defining the model with 4 clusters, 4 centroids 
model = KMeans(n_clusters = 4).fit(X_train)

#print label for each point
print("Labels:\n",model.labels_)

#print prediction on test set
prediction = model.predict(X_test)
print("Prediction:\n",prediction)

#printing coordinates of cluster centers
print("Cluster Center:\n",model.cluster_centers_)

Labels:
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 2 2 2 2 0 0 0
 0 0 0 2 2 2 0 2 2 2 2 2 2 3 3 3 2 3 0 3 0 3 3 3 3 3 0 3 3 3 0 3 0 3 0 3 0
 3]
Prediction:
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 2 2 2 2 2 0 0 2 2 2 0
 0 0 2 2 0 0 0 2 0 2 2 0 2 0 3 3 3 3 0 0 3 3 0 0 0 3 0 3 3 0 3 3 3 3 3 3 0
 0]
Cluster Center:
 [[6.33157895 2.86842105 4.81578947 1.63157895]
 [5.024      3.48       1.456      0.228     ]
 [5.50714286 2.64285714 4.01428571 1.26428571]
 [6.76470588 3.01764706 5.82941176 2.17647059]]
