# Implementing Multivariate Linear Regression using Normal Equation

**Importing necessary libraries and datasets**

In [13]:
import numpy as np
from sklearn import metrics, datasets
from sklearn.preprocessing import StandardScaler

In [14]:
X,y = datasets.load_boston(return_X_y = True)
X.shape

(506, 13)

**Dividing the data into training set and testing set**

In [15]:
X_train = X[0:400,:]

# create a temp array with all zeros of shape (400,14) for adding one extra column of ones
shape_tuple = (X_train.shape[0], X_train.shape[1] + 1);
X_temp = np.zeros(shape_tuple)
print(X_temp.shape)

# create a column vector of shape (400,1) containing all the ones for X0
column1 = np.ones(X_train.shape[0])
print(column1.shape)

# add this column as the first column of X_temp
X_temp[:,0] = column1;
print(X_temp)

# add the rest of the training data to it and finally assign it back to X_train
X_temp[:,1:] = X_train;
X_train = X_temp;
print(X_train.shape)


# getting our y_train vector
y_train = y[0:400]
print(y_train.shape)

(400, 14)
(400,)
[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]]
(400, 14)
(400,)


In [16]:
# remaining data will be our testing data

X_test = X[400:,:]
print(X_test.shape)

# create a temp array with all zeros of shape (400,14) for adding one extra column of ones
shape_tuple = (X_test.shape[0], X_test.shape[1] + 1);
X_temp = np.zeros(shape_tuple)

# create a column vector of shape (400,1) containing all the ones for X0
column1 = np.ones(X_test.shape[0])

# add this column as the first column of X_temp
X_temp[:,0] = column1;

# add the rest of the training data to it and finally assign it back to X_train
X_temp[:,1:] = X_test;
X_test = X_temp;
print(X_test.shape)

# getting our y_test vector
y_test = y[400:]
print(y_test.shape)

(106, 13)
(106, 14)
(106,)


**Performing feature scaling**

In [17]:
# initializing the theta vector with random uniform values between 0 and 1
# shape of theta is (14,1)
theta = np.random.uniform(0,1,X_train.shape[1])
print(theta)

# feature scaling the X_train data to bring the range of values of all columns in [0,1]
scaler = StandardScaler()

# ftting the data (i.e. finding out the mean and standard dev for normalization)
scaler.fit(X_train[:,1:])

# scaling the data and assigning it back to X_train and X_test
X_train[:,1:] = scaler.transform(X_train[:,1:])
X_test[:,1:] = scaler.transform(X_test[:,1:])

[7.61876394e-01 5.42441204e-04 3.49897535e-01 6.85954341e-01
 7.08761091e-01 4.42559752e-01 4.12520151e-01 6.89778479e-01
 5.65254106e-01 6.44641276e-01 3.31107132e-01 5.37984298e-01
 5.82169032e-01 4.88221293e-01]


**Applying Normal Equation**

In [18]:
lamb = 250
L = np.zeros((X_train.shape[1],X_train.shape[1]))
for i in range(1,L.shape[0]):
    L[i,i] = 1
A = np.linalg.pinv(np.dot(X_train.T,X_train) + (lamb * L))
B = np.dot(X_train.T,y_train)

theta = np.dot(A,B)
theta

array([24.3345    , -0.51293403,  0.49275107, -0.39355658,  0.59766748,
       -0.37157604,  2.73831488, -0.14346448, -0.9703047 ,  0.50597191,
       -0.36866427, -1.27004253,  0.21190041, -2.33481914])

**Testing our model**

In [19]:
prediction = np.dot(X_test,theta)

print("MAE", metrics.mean_absolute_error(y_true=y_test,y_pred = prediction))
print("MSE", metrics.mean_squared_error(y_true=y_test,y_pred = prediction))

MAE 3.8656976463937753
MSE 22.01574870698202
